//
// Created by john on 2020-02-12.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wyt_myapplication_Mp3Encoder */



#ifndef LAME_MP3ENCODER_H
#define LAME_MP3ENCODER_H
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wyt_myapplication_Mp3Encoder
 * Method:    init
 * Signature: (Ljava/lang/String;IIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jon_lame_Mp3Encoder_init
        (JNIEnv *, jobject, jstring, jint, jint, jint, jstring);

/*
 * Class:     com_wyt_myapplication_Mp3Encoder
 * Method:    encode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jon_lame_Mp3Encoder_encode
(JNIEnv *, jobject);

/*
 * Class:     com_wyt_myapplication_Mp3Encoder
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jon_lame_Mp3Encoder_destroy
(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif

#endif //LAME_MP3ENCODER_H